### ISSUE TITLE
Spanish translation.

### ISSUE THREAD

**Issue by vidimus** [Revokee/MOMTC#1]
Hello, @Revokee 

Any news about updating your scenario with the Spanish translation?

**Comment by vidimus** [comment]
Hello, @Revokee Ainda estou à espera...

**Comment by Revokee** [comment]
Looking into this now

**Comment by Revokee** [comment]
I added the files that Bola sent to me and they are now in this repo - soon should be available on Valkyrie.

**Comment by vidimus** [comment]
Great, it's already published. Thanks!
